---
title: webmeko
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  categories:
    title: categories
    output: true
  services:
    title: services
    output: true
  tags:
    title: tags
    output: true
email: viraj.chaudhary@apexure.com
description: web site using jekyll git and sithub and for cms we use siteleaf.
baseurl: "/webmeko.com"
url: https://virajchuaudhary.github.io
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
